### ISSUE TITLE
Update dependency on new version of dulwich

### ISSUE THREAD

**Issue by metatoaster** [PMR2/pmr2.wfctrl#2]
If/when the patches needed to make the thing go is done correctly at the upstream level, or that we can provide a monkey-patched version of code that we need to make this thing work with that.  This is needed due to acceptance of pull request #1.

**Comment by metatoaster** [comment]
@hsorby I've updated the dulwich usage to the current version of their API and threw it to the testing branch, and so far the CI via GitHub Actions seems to show that everything is in order.

I will be merging all of that in and cut a `0.4.0` release whenever.

**Comment by hsorby** [comment]
Awesome, sounds good to me.
